---
resources:
  - name: aladin-repo
    type: git
    source:
      uri: https://github.com/aladin16/ConcoursePipelineRepo.git
      branch: main

  - name: my-timer
    type: time
    source:
      interval: 2m

jobs:
  - name: job-hello-world-day-time
    public: true
    serial: true
    plan:
      - get: my-timer
        trigger: true
      - get: aladin-repo
      - task: edit-file
        file: aladin-repo/task_hello_world.yml


  - name: job-hello-world-night-time
    public: true
    serial: true
    plan:
      - get: my-timer
        trigger: true
      - get: aladin-repo
      - task: edit-file-2
        file: aladin-repo/task_hello_world.yml

