---
resources:
  - name: aladin-repo
    type: git
    source:
      uri: https://github.com/aladin16/ConcoursePipelineRepo.git
      branch: main

  - name: day-time
    type: time
    source:
      start: 8:55 AM
      stop: 9:15 AM
      location: America/Montreal

  - name: night-time
    type: time
    source:
      start: 9:30 AM
      stop: 3:00 PM
      location: America/Montreal

jobs:
  - name: job-hello-world-day-time
    public: true
    serial: true
    plan:
      - get: day-time
        trigger: true
      - get: aladin-repo
      - task: edit file
        file: task_hello_world.yml

  - name: job-hello-world-night-time
    public: true
    serial: true
    plan:
      - get: night-time
        trigger: true
      - get: aladin-repo
      - task: edit file 2
        file: task_hello_world.yml

  - name: job-hello-world-night-time
    public: true
    serial: true
    plan:
      - get: my-timer
        trigger: true
      - get: aladin-repo
      - task: edit-file-2
        file: aladin-repo/task_hello_world.yml