---
resources:
  - name: aladin-repo
    type: git
    source:
      uri: https://github.com/aladin16/ConcoursePipelineRepo.git
      branch: main

  - name: my-timer
    type: time
    source:
      interval: 1m

jobs:
  - name: job-hello-world-day-time
    public: true
    serial: true
    plan:
      - get: my-timer
        trigger: true
      - get: aladin-repo
      - task: edit-file
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: pypy}
          inputs:
            - name: aladin-repo
          outputs:
            - name: aladin-repo
          run:
            path: resource-tutorial/tutorials/basic/publishing-outputs/bump-timestamp-file.sh




